### ISSUE TITLE
Use color as state

### ISSUE THREAD

**Issue by s267562** [se2team3/PULSeBS#43]
In the calendar it can be useful to have a better feedback about the state of the lecture. I think it can be achieved using the colors as state (for example green - free, red - booked, gray - cancelled).

**Comment by lucarinelli** [comment]
We decided that it is more meaningful to have colors represent courses instead of states, all the not bookable lectures are going to be shown in a lighter or darker color, but we are not going to have a color for each state. We are also indicating the status in the box, so a color state could be overkill. And we are going to have new states going on (like 'waiting list'), too many colors can be confusing in that case.

Sorry
